### ISSUE TITLE
Somehow avoid duplication in docs websites?

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow.github.io#2]
e.g. `make_vers_switcher.py`

**Comment by cjfullerton** [comment]
Also matflows docs should be a superset of hpcflow documentation.

**Comment by fherreazcue** [comment]
Played with [subrepo](https://github.com/ingydotnet/git-subrepo) a bit and it worked nicely... maybe worth a try.

**Comment by fherreazcue** [comment]
I did a bit more tinkering and think we need to judge what we want...

Remote

- Need to have same file structure in all repos
- Can have multiple remotes pointing to the same folder
- Have to pull remote, then comit -- this can be a good thing
- Need to link and configure each remote... we could add a bash script

Subrepo

- Can clone subrepo to custom path in big repo.
- Cannot have multiple subrepos in the same folder (actually kind of designed to have its own "please do not touch" folder)
- When you pull the subrepo it automatically commits. -- can be a bad thing
- Developers do not need to link subrepos... they are already listed, subrepo handles it. (just need to have subrepo installed if you want to pull/push subrepos)
- Easy to push to subrepo 
  - DANGER, cannot have repo specific files for this... 
  - Using `git subrepo push` also creates a commit to the big repo, updating the .gitrepo file.
  - We could simply not use subrepo push... but there does not seem to be an equivalent to no-pushing setting
- If a change in subrepo is commited to the big repo it persists in that repo, even after a force pull... unless the subrepo has a newer commit.
- If there are other files in the subrepo folder, they get deleted on a force pull, or create a merge conflict on simple pull.

Submodule and Subtree requiere much more work and are widely not recommended...


So, if we use remotes, maybe we could add a bash script  that sets up all the remotes in the repo... it would only need to be used by developers...

If we go for subrepo, i'd recommend having a "no-touching-except-for-pulling" folder, and then move things outside that folder if needed.
I personally do not see this as much of an issue, the scripts could create output files in a separate folder... but maybe it is not worth the faff...

What do you think @aplowman @cjfullerton ?

**Comment by fherreazcue** [comment]
We decided to continue with remotes, but added a script to simplify syncing.

The script was added to hpcflow ([#507](https://github.com/hpcflow/hpcflow-new/pull/507)) and matflow ([#125](https://github.com/hpcflow/matflow-new/pull/125)).
