### ISSUE TITLE
Fix version sorting

### ISSUE THREAD

**Issue by fherreazcue** [hpcflow/hpcflow.github.io#4]
Currently they are being reverse-sorted [here](https://github.com/hpcflow/hpcflow.github.io/blob/defbfc4a533b607bc2192cbbb2f1f3fe60af41df/docs/make_vers_switcher.py#L6), but a simple sort does not appropriately deal with non-zero-padded numbers, and so version `v0.2.0a2` goes before `v0.2.0a23`, and `v0.2.0a1` before `v0.2.0a19`, for example.
![image](https://user-images.githubusercontent.com/36694679/226672492-d60707a5-53ae-42c5-ab9d-179304f727bb.png)

Either version numbers need to be padded with zeros (probably the easiest), or the sorting needs to do something clever by parsing the string (e.g. [using re.findall](https://github.com/nkmk/python-snippets/blob/077080d5686ee1731a477b282a7dc549333aebd2/notebook/sort_num_str_re.py#L31-L35), explained [here](https://note.nkmk.me/en/python-sort-num-str/)).

**Comment by aplowman** [comment]
I think changing the `sorted` key [here](https://github.com/hpcflow/hpcflow.github.io/blob/defbfc4a533b607bc2192cbbb2f1f3fe60af41df/docs/make_vers_switcher.py#L8) to this: 

```py
key=lambda i: int(re.search(r"a(\d+)", i + 'z').groups()[0]),
```

should do it!
